name: End-to-end tests
on: [push]
jobs:
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Code
        uses: actions/checkout@v3

      - name: Run Cypress test cases
        uses: cypress-io/github-action@v5
        with:
          command: npm run cypress:execution
          browser: chrome